spring:
  #设置开发环境
  profiles:
    active: dev

  security:
    user:
      name: admin  #默认的用户名
      password: 123456  #默认密码

# 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

  mapper-locations: classpath:mapper/**Mapper.xml